"""initial schema

Revision ID: 1ce30ff1e59b
Revises: 
Create Date: 2026-03-28 19:34:12.234470
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ce30ff1e59b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('max_bots', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('broker_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('metaapi_account_id', sa.String(length=100), nullable=False),
    sa.Column('mt5_login', sa.String(length=50), nullable=False),
    sa.Column('mt5_server', sa.String(length=100), nullable=False),
    sa.Column('broker_name', sa.String(length=50), server_default=sa.text("'exness'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('lot_size', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_lot_size', sa.Numeric(precision=10, scale=4), server_default=sa.text('0.1'), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Numeric(precision=5, scale=2), server_default=sa.text('5.00'), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('lookback_bars', sa.Integer(), server_default=sa.text('200'), nullable=False),
    sa.Column('is_live', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'stopped'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_logs_bot_id'), 'bot_logs', ['bot_id'], unique=False)
    op.create_index('ix_bot_logs_bot_id_created_at', 'bot_logs', ['bot_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bot_logs_created_at'), 'bot_logs', ['created_at'], unique=False)
    op.create_table('bot_trades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('lot_size', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=5), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=5), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=20, scale=5), nullable=True),
    sa.Column('signal', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_trades_bot_id'), 'bot_trades', ['bot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_trades_bot_id'), table_name='bot_trades')
    op.drop_table('bot_trades')
    op.drop_index(op.f('ix_bot_logs_created_at'), table_name='bot_logs')
    op.drop_index('ix_bot_logs_bot_id_created_at', table_name='bot_logs')
    op.drop_index(op.f('ix_bot_logs_bot_id'), table_name='bot_logs')
    op.drop_table('bot_logs')
    op.drop_table('bots')
    op.drop_table('scripts')
    op.drop_table('broker_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
