"""add mt5_password_encrypted to broker_accounts

Revision ID: 2e3942f97626
Revises: e86f301bfdfd
Create Date: 2026-04-04 23:44:24.477520
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3942f97626'
down_revision: Union[str, None] = 'e86f301bfdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('mt5_password_encrypted', sa.Text(), nullable=True))
    op.alter_column('broker_accounts', 'metaapi_account_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('broker_accounts', 'metaapi_account_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('broker_accounts', 'mt5_password_encrypted')
    # ### end Alembic commands ###
